name: docker-build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: arm64

      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1

      -
        name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
